Pull Request 6802904: Bug 37362056: XSAPI / libHttpClient: split props var when building for source so PF & others can build libHttpClient from source, but not XSAPI
PlayFab/PlayFabCoreCSdk pull request #5
Opened 2022-01-03 19:33 UTC by jasonsandlin

2022-01-03 23:41 UTC, jplafonta requested changes

2022-01-03 23:41 UTC, jplafonta commented on build/GDK/TestClientApp.vcxproj
> +    <LibHttpClientBuildFromSource>true</LibHttpClientBuildFromSource>
Won't this break until the GDK props file is updated?

2022-01-06 23:05 UTC, jasonsandlin commented on build/GDK/TestClientApp.vcxproj
> +    <LibHttpClientBuildFromSource>true</LibHttpClientBuildFromSource>
right.  fixed

2022-01-06 23:06 UTC, jplafonta approved these changes

2022-01-06 23:08 UTC, merged